# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         DBD-Pg
version:      1.42_1
version_from: Pg.pm
installdirs:  site
requires:
    Test::Harness:                 2.03
    Test::Simple:                  0.17

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
